"""Tests for fxtcombine sensitivity-map workflow integration."""

from __future__ import annotations

import sys

import pytest

from fxtcombine import pipeline
from fxtsensmap import DEFAULT_ECF, sigma_to_likemin


def _parse_fxtcombine_args(extra_args: list[str] | None = None):
    """Parse a minimal ``fxtcombine`` command line.

    Parameters
    ----------
    extra_args : list[str] | None, optional
        Additional command-line arguments.

    Returns
    -------
    argparse.Namespace
        Parsed arguments.
    """
    argv = [
        "input",
        "--ra",
        "1.0",
        "--dec",
        "2.0",
        "--obsid-lst",
        "0001",
    ]
    if extra_args:
        argv.extend(extra_args)
    return pipeline.build_parser().parse_args(argv)


def test_fxtcombine_parser_enables_sensmap_by_default() -> None:
    """The stacked sensitivity map and quickview should be generated by default.

    Returns
    -------
    None
    """
    args = _parse_fxtcombine_args()

    assert args.disable_sensmap is False
    assert args.sens_eef == pytest.approx(0.90)
    assert args.sens_ecf == pytest.approx(DEFAULT_ECF)
    assert args.sens_likemin is None
    assert args.sens_sigma is None
    assert pipeline._resolve_sensmap_likemin(args.sens_likemin, args.sens_sigma) == pytest.approx(6.0)
    assert args.disable_quickview is False
    assert args.quickview_out is None
    assert args.quickview_dpi == 100


def test_fxtcombine_parser_accepts_sensmap_overrides() -> None:
    """Sensitivity-map generation should expose the planned CLI knobs.

    Returns
    -------
    None
    """
    args = _parse_fxtcombine_args(
        [
            "--disable-sensmap",
            "--sens-eef",
            "0.75",
            "--sens-ecf",
            "123.5",
            "--sens-likemin",
            "8.0",
        ]
    )

    assert args.disable_sensmap is True
    assert args.sens_eef == pytest.approx(0.75)
    assert args.sens_ecf == pytest.approx(123.5)
    assert args.sens_likemin == pytest.approx(8.0)
    assert args.sens_sigma is None


def test_fxtcombine_parser_accepts_sensmap_sigma() -> None:
    """Sensitivity-map generation should accept Gaussian-equivalent sigma.

    Returns
    -------
    None
    """
    args = _parse_fxtcombine_args(["--sens-sigma", "3.0"])

    assert args.sens_likemin is None
    assert args.sens_sigma == pytest.approx(3.0)
    assert pipeline._resolve_sensmap_likemin(args.sens_likemin, args.sens_sigma) == pytest.approx(sigma_to_likemin(3.0))


def test_fxtcombine_parser_accepts_quickview_overrides(tmp_path) -> None:
    """Quickview generation should expose final-QA CLI controls.

    Parameters
    ----------
    tmp_path : pathlib.Path
        Temporary directory.

    Returns
    -------
    None
    """
    quickview_out = tmp_path / "qa.png"
    args = _parse_fxtcombine_args(
        [
            "--disable-quickview",
            "--quickview-out",
            str(quickview_out),
            "--quickview-dpi",
            "180",
        ]
    )

    assert args.disable_quickview is True
    assert args.quickview_out == str(quickview_out)
    assert args.quickview_dpi == 180


def test_fxtcombine_parser_rejects_sensmap_threshold_conflict() -> None:
    """Sensitivity likelihood and sigma options should be mutually exclusive.

    Returns
    -------
    None
    """
    with pytest.raises(SystemExit):
        _parse_fxtcombine_args(["--sens-likemin", "6.0", "--sens-sigma", "3.0"])


def test_main_forwards_sensmap_options(monkeypatch, tmp_path) -> None:
    """The CLI entry point should pass sensitivity-map options to the pipeline.

    Parameters
    ----------
    monkeypatch : pytest.MonkeyPatch
        Fixture used to intercept the pipeline call.
    tmp_path : pathlib.Path
        Temporary directory.

    Returns
    -------
    None
    """
    captured = {}

    def _fake_fxtcombine_pipeline(**kwargs):
        captured.update(kwargs)

    monkeypatch.setattr(pipeline, "build_cli_logger", lambda *args, **kwargs: None)
    monkeypatch.setattr(pipeline, "fxtcombine_pipeline", _fake_fxtcombine_pipeline)
    monkeypatch.setattr(
        sys,
        "argv",
        [
            "fxtcombine",
            str(tmp_path),
            "--ra",
            "1.0",
            "--dec",
            "2.0",
            "--obsid-lst",
            "0001",
            "--disable-sensmap",
            "--sens-eef",
            "0.75",
            "--sens-ecf",
            "123.5",
            "--sens-likemin",
            "8.0",
        ],
    )

    pipeline.main()

    assert captured["make_sensmap"] is False
    assert captured["sens_eef"] == pytest.approx(0.75)
    assert captured["sens_ecf"] == pytest.approx(123.5)
    assert captured["sens_likemin"] == pytest.approx(8.0)
    assert captured["sens_sigma"] is None
    assert captured["make_quickview"] is True
    assert captured["quickview_out"] is None
    assert captured["quickview_dpi"] == 100


def test_main_forwards_sensmap_sigma(monkeypatch, tmp_path) -> None:
    """The CLI entry point should pass sensitivity sigma to the pipeline.

    Parameters
    ----------
    monkeypatch : pytest.MonkeyPatch
        Fixture used to intercept the pipeline call.
    tmp_path : pathlib.Path
        Temporary directory.

    Returns
    -------
    None
    """
    captured = {}

    def _fake_fxtcombine_pipeline(**kwargs):
        captured.update(kwargs)

    monkeypatch.setattr(pipeline, "build_cli_logger", lambda *args, **kwargs: None)
    monkeypatch.setattr(pipeline, "fxtcombine_pipeline", _fake_fxtcombine_pipeline)
    monkeypatch.setattr(
        sys,
        "argv",
        [
            "fxtcombine",
            str(tmp_path),
            "--ra",
            "1.0",
            "--dec",
            "2.0",
            "--obsid-lst",
            "0001",
            "--sens-sigma",
            "3.0",
        ],
    )

    pipeline.main()

    assert captured["sens_likemin"] is None
    assert captured["sens_sigma"] == pytest.approx(3.0)


def test_main_forwards_quickview_options(monkeypatch, tmp_path) -> None:
    """The CLI entry point should pass quickview options to the pipeline.

    Parameters
    ----------
    monkeypatch : pytest.MonkeyPatch
        Fixture used to intercept the pipeline call.
    tmp_path : pathlib.Path
        Temporary directory.

    Returns
    -------
    None
    """
    captured = {}
    quickview_out = tmp_path / "quickview-custom.png"

    def _fake_fxtcombine_pipeline(**kwargs):
        captured.update(kwargs)

    monkeypatch.setattr(pipeline, "build_cli_logger", lambda *args, **kwargs: None)
    monkeypatch.setattr(pipeline, "fxtcombine_pipeline", _fake_fxtcombine_pipeline)
    monkeypatch.setattr(
        sys,
        "argv",
        [
            "fxtcombine",
            str(tmp_path),
            "--ra",
            "1.0",
            "--dec",
            "2.0",
            "--obsid-lst",
            "0001",
            "--disable-quickview",
            "--quickview-out",
            str(quickview_out),
            "--quickview-dpi",
            "180",
        ],
    )

    pipeline.main()

    assert captured["make_quickview"] is False
    assert captured["quickview_out"] == str(quickview_out)
    assert captured["quickview_dpi"] == 180


def test_build_fxtsensmap_command() -> None:
    """The Stage-6 command should target the stacked products.

    Returns
    -------
    None
    """
    cmd = pipeline._build_fxtsensmap_command(
        "/tmp/stack bkg.fits",
        "/tmp/stack expmap.fits",
        "/tmp/stack psfprod.fits",
        "/tmp/stack sensmap.fits",
        0.9,
        DEFAULT_ECF,
        6.0,
        jobs=4,
        mask="/tmp/stack mask.fits",
    )

    assert cmd == (
        'fxtsensmap --bkgmap "/tmp/stack bkg.fits" '
        '--expmap "/tmp/stack expmap.fits" '
        '--psfprod "/tmp/stack psfprod.fits" '
        "--eef 0.9 "
        f"--ecf {float(DEFAULT_ECF)} "
        "--likemin 6.0 "
        "--jobs 4 "
        '--mask "/tmp/stack mask.fits" '
        '--out "/tmp/stack sensmap.fits"'
    )


def test_build_quickview_command() -> None:
    """The Stage-7 command should target quickview output and log paths.

    Returns
    -------
    None
    """
    cmd = pipeline._build_quickview_command(
        "/tmp/stack dir",
        "/tmp/stack dir/quickview.png",
        dpi=180,
        log_file="/tmp/stack dir/quickview.log",
    )

    assert cmd == (
        'fxtcombine-quickview "/tmp/stack dir" '
        '--out "/tmp/stack dir/quickview.png" '
        "--dpi 180 "
        '--log-file "/tmp/stack dir/quickview.log"'
    )
    assert "--r90-stride" not in cmd


def test_run_quickview_stage_warns_without_raising(monkeypatch, tmp_path) -> None:
    """Quickview failures should be reported without failing completed products.

    Parameters
    ----------
    monkeypatch : pytest.MonkeyPatch
        Fixture used to replace command execution.
    tmp_path : pathlib.Path
        Temporary directory.

    Returns
    -------
    None
    """

    def _raise_run_cmd(cmd: str, logger=None, logname=None, cwd=None):
        raise RuntimeError("plot failed")

    monkeypatch.setattr(pipeline, "run_cmd", _raise_run_cmd)

    ok = pipeline._run_quickview_stage(str(tmp_path), str(tmp_path / "quickview.png"), dpi=100, logger=None)

    assert ok is False


def test_build_fxtsensmap_command_with_sigma() -> None:
    """The Stage-6 command should pass sigma instead of likemin when requested.

    Returns
    -------
    None
    """
    cmd = pipeline._build_fxtsensmap_command(
        "/tmp/stack bkg.fits",
        "/tmp/stack expmap.fits",
        "/tmp/stack psfprod.fits",
        "/tmp/stack sensmap.fits",
        0.9,
        DEFAULT_ECF,
        None,
        jobs=4,
        mask="/tmp/stack mask.fits",
        sigma=3.0,
    )

    assert cmd == (
        'fxtsensmap --bkgmap "/tmp/stack bkg.fits" '
        '--expmap "/tmp/stack expmap.fits" '
        '--psfprod "/tmp/stack psfprod.fits" '
        "--eef 0.9 "
        f"--ecf {float(DEFAULT_ECF)} "
        "--sigma 3.0 "
        "--jobs 4 "
        '--mask "/tmp/stack mask.fits" '
        '--out "/tmp/stack sensmap.fits"'
    )
